### ISSUE TITLE
 2400 requests per minute. Please use the websocket for live updates to avoid polling the API

### ISSUE THREAD

**Issue by kandangjamur** [Djarrieta/donbot-hedge#1]
Nice script!

but often get this error.

do you know how to resolve this issue? Thanks

**Comment by Djarrieta** [comment]
It looks like you only can have one instance per IP. How many instances are you running? You can not for example run backtesting and trade in the same time, it has to be one at the time. It is running nice and with no errors in my server, anyways, it looks like the strategy or the managment is not that good yet. I am running 2 users in one instance. Let me know if you are running once instance at the time.

**Comment by kandangjamur** [comment]
Hi [Djarrieta](https://github.com/Djarrieta), 
Thanks for the reply, ah you right it's run at the same time. it run well now.

And you also right about the management is not that good yet. when it in hedge mode. the TP and SL is disappear for both side. it would be good if the bot can still have the SL in hedge mode and update the SL back to entry price for profit position(+). it's okay to have little loss than have a big loss.

**Comment by Djarrieta** [comment]
If you have ideas how to improve it, collaboration is wellcome. If you have ideas, but don't have time, we can talk. Probable I can implement it. This is a really fun side project. I have been learning about a lot of things with this one. Any help is wellcome.

**Comment by Djarrieta** [comment]
BTW the idea behind having open positions with the same amount in both directions is "freeze" the losses. In this case, no matter what happend with the price, one order is going to be winning and another lossing, the diferences is going to be the same with time, it allows me resolve it manually later or assume the loss when a good day comes.
